### ISSUE TITLE
Pod support

### ISSUE THREAD

**Issue by JamesLeeTrigg** [matrejek/SwiftEntitlements#1]
I would like to use this inside a pod I am creating to share keys between apps.
Is it possible to fork this project or for you to create a cocoa pod version?

**Comment by matrejek** [comment]
hi @JamesLeeTrigg  and thank you for your interest in this repository. I have added a spec into the repository. Also pushed it to the Specs repo here: https://github.com/CocoaPods/Specs/commit/05e213de9f8fb87d78c787baf60432f10cb30fe2

**Comment by JamesLeeTrigg** [comment]
Thanks

**Comment by matrejek** [comment]
You're welcome! I will test it later as my repo snapshot does not seem to have that version yet.

**Comment by matrejek** [comment]
The package should be now available with Specs repo as well. Enjoy!
